# my-secret.yaml
# This Secret stores a username and password, encoded in base64.

apiVersion: v1
kind: Secret
metadata:
  name: my-app-credentials # The name of the Secret object
type: Opaque # Opaque is the default type for arbitrary user-defined data

data:
  username: bXl1c2Vy # base64 encoded value of "myuser"
  password: c3VwZXJzZWNyZXRwYXNz # base64 encoded value of "supersecretpass"
