# nginx-secret-demo.yaml
# This deployment demonstrates how to use Kubernetes Secrets
# as environment variables and as mounted files inside a Pod.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-secret-demo # Name of the Deployment
spec:
  replicas: 1 # Run one instance of the Pod
  selector:
    matchLabels:
      app: nginx-secret-demo # Used to match the Pod template below
  template:
    metadata:
      labels:
        app: nginx-secret-demo # Labels assigned to the Pod
    spec:
      containers:
        - name: nginx # Container name
          image: nginx:latest # Using the latest Nginx image
          ports:
            - containerPort: 80 # Exposing port 80 inside the container

          # Inject secret values as environment variables
          env:
            - name: MY_APP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-app-credentials # Name of the Secret
                  key: username # Key inside the Secret

            - name: MY_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-credentials
                  key: password

          # Mount the entire Secret as files in a directory
          volumeMounts:
            - name: secret-volume # Must match the volume name below
              mountPath: "/etc/app-secrets" # Mount location inside the container
              readOnly: true # Prevent writing to this directory

      volumes:
        - name: secret-volume
          secret:
            secretName: my-app-credentials # Reference to the Secret created earlier
