apiVersion: v1
kind: Pod
metadata:
  name: nginx-v1-dev-pod
  labels:
    app: nginx
    environment: dev
    version: "1.0"
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:1.20
      ports:
        - containerPort: 80
