apiVersion: v1
kind: Pod
metadata:
  name: nginx-v2-prod-pod
  labels:
    app: nginx
    environment: prod
    version: "2.0"
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:1.22 # Use a slightly different version
      ports:
        - containerPort: 80
