apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-data-pvc
spec:
  accessModes:
    - ReadWriteOnce # This volume can be mounted as read-write by a single node
  storageClassName: my-fast-storage # Referencing our custom StorageClass
  resources:
    requests:
      storage: 100Mi # Requesting 100 Mebibytes of storage
