# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-persistent-storage
              mountPath: /usr/share/nginx/html # Nginx serves content from here
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi" # Request 128 MiB of memory
            limits:
              cpu: "200m" # Limit to 200 millicores (0.2 CPU cores)
              memory: "256Mi" # Limit to 256 MiB of memory
      volumes:
        - name: nginx-persistent-storage
          persistentVolumeClaim:
            claimName: nginx-data-pvc # Referencing our PVC
