apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-workers

spec:
  completions: 5 # Total number of successful Pods required
  parallelism: 2 # Max number of Pods running at once
  ttlSecondsAfterFinished: 60 # Auto-delete job/pods 60 seconds after completion

  template:
    spec:
      containers:
        - name: worker-container
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "Worker $(hostname) processing...";
              sleep 3;
              echo "Worker $(hostname) finished."
      restartPolicy:
        OnFailure # If the container fails, Kubernetes will restart the Pod;
        # The Job will keep retrying failed Pods until all completions are met
