# 02-nginx-producer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-producer-app
  namespace: service-producer
  labels:
    app: nginx-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-producer
  template:
    metadata:
      labels:
        app: nginx-producer
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-producer-service
  namespace: service-producer
spec:
  selector:
    app: nginx-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
