apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: NodePort # Expose internally within the cluster
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30120
      protocol: TCP
  selector:
    app: guestbook
    tier: frontend
