apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None # This makes it a headless service
  selector:
    app: redis
