apiVersion: v1
kind: Pod
metadata:
  name: inspect-hostpath
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: pvc-storage
          mountPath: /mnt/host
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: my-pvc
