apiVersion: v1
kind: Pod
metadata:
  name: demo-pv-pod
spec:
  containers:
    - name: writer
      image: busybox
      command:
        [
          "sh",
          "-c",
          "echo 'Persistent data created on $(date)' > /data/demo.txt && sleep 3600",
        ]
      volumeMounts:
        - mountPath: /data
          name: demo-storage
  volumes:
    - name: demo-storage
      persistentVolumeClaim:
        claimName: my-pvc
