# my-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-page
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to My App!</title>
      <style>
        body { font-family: Arial, sans-serif; background-color: #f0f0f0; text-align: center; padding-top: 50px; }
        .container { background-color: #ffffff; margin: auto; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); max-width: 600px; }
        h1 { color: #333; }
        p { color: #666; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Hello from our Kubernetes ConfigMap!</h1>
        <p>This page was served by Nginx, and its content came directly from a ConfigMap.</p>
        <p>This shows how easy it is to update content without touching the Docker image!</p>
      </div>
    </body>
    </html>
