apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-noprobe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-noprobe
  template:
    metadata:
      labels:
        app: nginx-noprobe
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
